trigger: none
pr: none

parameters:
  - name: vms
    type: object
    default: ["ubuntu1","windows-1"]

pool:
  vmImage: ubuntu-latest

jobs:
- job: startvmjob
  displayName: Start VMs
    
  steps: 
  - checkout: none
  
  - ${{ each vm in parameters.vms }}:
    - task: AzureCLI@2
      displayName: starting vm ${{vm}}
      inputs:
        azureSubscription: 'AzureMSDN-ADO Intro'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $vmrequest = az vm list | ConvertFrom-Json | Where-Object {$_.Name -Match "${{vm}}"}
          az vm start --resource-group $vmrequest.resourcegroup --name $vmrequest.name