trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- task: PythonScript@0
  displayName: print datetime using python
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(Build.SourcesDirectory)/python/print_datetime.py'
