
trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo '$(Build.BuildNumber)'
  displayName: display build number
- task: PowerShell@2
  displayName: change build number
  inputs:
    targetType: 'inline'
    script: |
      $buildnumber = -join("v","Gerasimos","_","$(Build.BuildNumber)")
      Write-Host "##vso[build.updatebuildnumber]$buildnumber"